### ISSUE TITLE
Joins/Relationships

### ISSUE THREAD

**Issue by fyroc** [GonistLelatel/xpdo#1]
Do you have any examples of relating one model to another? Is this possible with xpdo? I would love to use it for my framework, but this feature is essential.

**Comment by GonistLelatel** [comment]
The "relating one model to another" needs more complex logic and tools.
The php frameworks use console utils to generate relations maps.
And the frameworks use some xml, or json files to configurate databases layers.
Now i havent ideas how to make simple this case of "relating one  or many model" without write additional tools.
My main idea: "make simple layer of PDO, and make table rows like objects".

**Comment by GonistLelatel** [comment]
But i will try some code experiments, if i will found the solution, i will implement it.

**Comment by GonistLelatel** [comment]
v 1.0.11:  implemented the relations, closed.
